#!/bin/sh

rm -f build_info.h
echo '/* autogenerated by make-build-info.sh */' > build_info.h
echo 'const char *REVISION = "'$(git rev-parse HEAD)'";' >> build_info.h
echo 'const char *BUILD_DATE = "'$(date +%Y%m%d-%H%M%S)'";' >> build_info.h
